[package]
name = "echo"
version = "0.1.0"
edition = "2024"
description = "A terminal RSVP reader written in Rust"
license = "MIT"
repository = "https://github.com/aagrawal207/echo"

[[bin]]
name = "ech"
path = "src/main.rs"

[dependencies]
crossterm = "0.29.0"
pulldown-cmark = { version = "0.13.3", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
toml = { version = "1.1.2", default-features = false, features = ["parse", "serde"] }
